### PR TITLE
Coverage test

### PR DESCRIPTION
**Pull request by byronchien**
- added make check to automatically call gcov and count all the coverage
- includes test_script.sh and parse_coverage.py

### CODE REVIEW

**Comment by nathanielchu** [comment]
looks good

**Comment by konradjniemiec** [comment]
Looks good, is there a way to measure the coverage on the .h files? Should be pretty full coverage.

**Comment by byronchien** [comment]
When I checked, most of the .h files had zero coverage so I felt like it wasn't helpful, but I can write some tests to specifically target the inline functions in the headers.

**Comment by byronchien** [comment]
Header files now included in the coverage. The script now doesn't account for the nginx-configparser and googletest in the coverage count.

**Pull request merged**
