### PR TITLE
add proxyHandler and fix some bugs

### PR DESCRIPTION
**Pull request by caraxin**

### CODE REVIEW

**Comment by caraxin** [comment]
I fix some bugs in your previous EchoHandler and StaticHandler.
For StaticHandler, your previous implementation doesn't support like:
  path /static StaticHandler {
    root /static;
  }
In Connection, you have bugs in start_writing. 
and also some other small bugs.

Now ProxyHandler can realize the basic functions, but still have some problem in fetching some css files. I am trying to handle it. 
The proxyHandler is configured in configure_file.

**Comment by konradjniemiec** [comment]
Is this in addition to the latest pull request? It appears as if the other one has the same initial commit.

**Comment by caraxin** [comment]
@konradjniemiec i think he add some integration tests for ProxyHandler and then checkout a new branch from mine. you can just look at the latest pull request. Thanks.

**Comment by konradjniemiec** [comment]
OK I'll close this one then.

**Pull request closed without merging**
