### PR TITLE
parser now parses path

### PR DESCRIPTION
**Pull request by byronchien**
used the following config:
```
server {
	listen 4000;
	server_name 127.0.0.1;
}

path /echo EchoHandler;
path /static StaticFileHandler {
	root ~/files;
}
```

the echohandler and staticfilehandler are now included in the valuepairs vector as {"/echo", "EchoHandler"}, {"/static", "StaticFileHandler"}, and {"root", "~/files"}

### CODE REVIEW

**Comment by nathanielchu** [comment]
uncomment run and take out the print statements?

**Comment by konradjniemiec** [comment]
This won't work with multiple handlers for EchoHandler for example. because they are value pairs, they will conflict.

**Comment by byronchien** [comment]
should i just store all the echohandler / statichandlers in a separate vector like request config then?

**Comment by nathanielchu** [comment]
I think you should store echohandler / statichandlers in a request config vector

**Comment by byronchien** [comment]
aite will make the changes in another branch since this current one doesn't have the requestconfig stuff

**Pull request closed without merging**
